import { db } from './db';

export async function seedDatabase() {
  const existing = await db.modules.count();
  if (existing > 0) return;

  const modules = [
    { id: 1, title: 'Claude 101', slug: 'claude-101', description: 'Introduction to Claude models, capabilities, and core concepts', order: 1 },
    { id: 2, title: 'Claude Code 101', slug: 'claude-code-101', description: 'Getting started with Claude Code for development workflows', order: 2 },
    { id: 3, title: 'Claude Code in Action', slug: 'claude-code-action', description: 'Advanced Claude Code patterns and real-world use cases', order: 3 },
    { id: 4, title: 'Building with the Claude API', slug: 'claude-api', description: 'Core API concepts, authentication, messages, and streaming', order: 4 },
    { id: 5, title: 'Introduction to MCP', slug: 'mcp-intro', description: 'Model Context Protocol fundamentals and architecture', order: 5 },
    { id: 6, title: 'MCP Advanced Topics', slug: 'mcp-advanced', description: 'Advanced MCP patterns, custom servers, and production deployment', order: 6 },
    { id: 7, title: 'Introduction to Agent Skills', slug: 'agent-skills', description: 'Understanding and building agent skills for Claude', order: 7 },
    { id: 8, title: 'Introduction to Subagents', slug: 'subagents', description: 'Orchestrating subagents for complex task decomposition', order: 8 },
    { id: 9, title: 'AI Fluency Foundations', slug: 'ai-fluency', description: 'AI Fluency framework: capabilities, limitations, and responsible use', order: 9 },
    { id: 10, title: 'Claude Cowork', slug: 'claude-cowork', description: 'Collaborative AI workflows with Claude Cowork', order: 10 },
    { id: 11, title: 'AI Capabilities & Limitations', slug: 'ai-capabilities', description: 'Deep dive into what Claude can and cannot do', order: 11 },
    { id: 12, title: 'Claude on Cloud Platforms', slug: 'claude-cloud', description: 'Deploying Claude via AWS Bedrock and Google Cloud Vertex AI', order: 12 },
    { id: 13, title: 'Teaching AI Fluency', slug: 'teaching-ai', description: 'How to teach AI fluency to teams and organizations', order: 13 },
  ];

  await db.modules.bulkAdd(modules);

  // Flashcards
  const flashcards: any[] = [
    // Module 1: Claude 101
    { moduleId: 1, title: 'Claude Model Family', content: 'Claude is a family of large language models developed by Anthropic. The current generation includes Claude Opus (most powerful), Claude Sonnet (balanced), and Claude Haiku (fastest, most cost-effective). Each model is designed for different use cases based on the trade-off between capability, speed, and cost.', keyPoints: ['Opus: highest capability, best for complex reasoning', 'Sonnet: balanced performance and cost', 'Haiku: fastest, most economical for high-volume tasks', 'Models are named after musical compositions (Anthropic tradition)', 'Each model has different context window sizes and pricing'], order: 1 },
    { moduleId: 1, title: 'Context Windows & Token Limits', content: 'The context window is the amount of text Claude can process in a single request. Claude models support up to 200K tokens context window. Understanding context windows is critical for architecting applications - you must fit your system prompt, conversation history, tool definitions, and user input within this limit.', keyPoints: ['200K token context window for Claude models', 'Tokens include system prompt, history, tools, and user input', 'Longer context = higher cost and potentially higher latency', 'Context management is a key architectural concern', 'Strategies: summarization, sliding window, RAG'], order: 2 },
    { moduleId: 1, title: 'Core Capabilities', content: 'Claude excels at text generation, analysis, summarization, translation, coding, mathematical reasoning, and creative writing. It can follow complex instructions, maintain context across long conversations, and reason about nuanced topics. Claude is also trained to be helpful, harmless, and honest (Constitutional AI).', keyPoints: ['Text generation and analysis', 'Code generation and debugging', 'Mathematical and logical reasoning', 'Multi-language support', 'Constitutional AI training for safety'], order: 3 },

    // Module 2: Claude Code 101
    { moduleId: 2, title: 'What is Claude Code', content: 'Claude Code is an agentic coding tool that lives in your terminal. It can read your codebase, edit files, run commands, and execute multi-step coding tasks. Unlike simple code completion, Claude Code understands your entire project context and can autonomously work through complex development tasks.', keyPoints: ['Terminal-based agentic coding assistant', 'Reads and edits entire codebases', 'Executes shell commands autonomously', 'Understands project context and dependencies', 'Supports interactive and headless (CI/CD) modes'], order: 1 },
    { moduleId: 2, title: 'Claude Code Permissions', content: 'Claude Code uses a permission system to control what actions it can take. Users can allow or deny file reads, file writes, bash commands, and network requests. This security model ensures Claude Code cannot make unauthorized changes. Permissions can be set per-project via CLAUDE.md or .claude/settings.json.', keyPoints: ['Permission system for reads, writes, commands, network', 'CLAUDE.md for project-level instructions', '.claude/settings.json for configuration', 'Interactive approval or pre-approval modes', 'Critical for safe agentic operation'], order: 2 },
    { moduleId: 2, title: 'CLAUDE.md Configuration', content: 'CLAUDE.md is a markdown file placed in your project root that provides persistent instructions to Claude Code. It can define coding standards, project architecture, preferred libraries, and behavioral guidelines. This is the primary way to customize Claude Code behavior for your specific project.', keyPoints: ['Project-level instruction file in markdown', 'Defines coding standards and conventions', 'Specifies project architecture and patterns', 'Can include behavioral guidelines', 'Loaded automatically when Claude Code starts'], order: 3 },

    // Module 3: Claude Code in Action
    { moduleId: 3, title: 'Multi-file Editing', content: 'Claude Code can edit multiple files in a single task, understanding dependencies between them. For example, when adding a new API endpoint, it can create the route handler, update the router, add tests, and modify the data model - all while maintaining consistency across files.', keyPoints: ['Cross-file dependency understanding', 'Consistent changes across codebase', 'Can handle complex refactoring tasks', 'Maintains code style and patterns', 'Reduces manual coordination overhead'], order: 1 },
    { moduleId: 3, title: 'Headless Mode & CI/CD', content: 'Claude Code can run in headless mode via the -p flag, accepting a prompt and returning output. This enables integration into CI/CD pipelines, automated testing, and batch processing. Headless mode is essential for production workflows where human interaction is not feasible.', keyPoints: ['-p flag for headless execution', 'CI/CD pipeline integration', 'Automated code review and fixes', 'Batch processing capabilities', 'Returns structured output for automation'], order: 2 },
    { moduleId: 3, title: 'Custom Skills in Claude Code', content: 'Claude Code supports custom skills - reusable instruction sets that extend its capabilities. Skills are defined in markdown files and can include scripts, templates, and reference materials. They allow teams to encode domain-specific knowledge and workflows.', keyPoints: ['Reusable instruction sets in markdown', 'Can include scripts and templates', 'Domain-specific knowledge encoding', 'Team-shared workflow definitions', 'Extends Claude Code beyond default capabilities'], order: 3 },

    // Module 4: Building with the Claude API
    { moduleId: 4, title: 'Messages API', content: 'The Messages API is the primary interface for interacting with Claude. It accepts an array of messages with roles (user, assistant) and returns a completion. The API supports system prompts, multi-turn conversation history, and structured content blocks (text, images, tool results).', keyPoints: ['Primary API endpoint for Claude interactions', 'Messages array with user/assistant roles', 'System prompt for behavior configuration', 'Supports text and image content blocks', 'Multi-turn conversation support'], order: 1 },
    { moduleId: 4, title: 'Tool Use (Function Calling)', content: 'Claude can use tools by generating structured tool_use blocks in its response. The application executes the tool, returns the result as a tool_result, and Claude continues its response. This enables Claude to interact with external systems, databases, APIs, and perform actions beyond text generation.', keyPoints: ['Claude generates tool_use blocks', 'Application executes the tool', 'Results returned as tool_result', 'Enables external system interaction', 'Core mechanism for building agents'], order: 2 },
    { moduleId: 4, title: 'Streaming Responses', content: 'The API supports server-sent events (SSE) streaming, delivering tokens as they are generated. Streaming improves perceived latency and enables real-time user experiences. The streaming format includes content_block_start, content_block_delta, and content_block_stop events.', keyPoints: ['SSE streaming for real-time token delivery', 'Improves perceived latency', 'Events: content_block_start, delta, stop', 'Essential for chat applications', 'Can stream text and tool use blocks'], order: 3 },
    { moduleId: 4, title: 'Authentication & Rate Limits', content: 'API authentication uses the x-api-key header with an Anthropic API key. Rate limits are enforced per organization based on usage tier. Understanding rate limits is critical for production architecture - you may need request queuing, caching, or load balancing across multiple keys.', keyPoints: ['x-api-key header authentication', 'Rate limits per organization and tier', 'Usage tiers: Free, Tier 1-4', 'Production apps need rate limit handling', 'Consider caching and request queuing'], order: 4 },

    // Module 5: Introduction to MCP
    { moduleId: 5, title: 'What is MCP', content: 'Model Context Protocol (MCP) is an open protocol for connecting AI applications to external data sources and tools. It standardizes how AI models access context, replacing ad-hoc integrations with a universal interface. MCP was introduced by Anthropic and is now an open standard with broad industry adoption.', keyPoints: ['Open protocol for AI-tool integration', 'Standardizes context access for AI models', 'Introduced by Anthropic, now open standard', 'Replaces ad-hoc integrations', 'Broad industry adoption'], order: 1 },
    { moduleId: 5, title: 'MCP Architecture', content: 'MCP uses a client-server architecture. MCP clients (like Claude Code, Claude Desktop) connect to MCP servers that expose resources, tools, and prompts. The protocol uses JSON-RPC 2.0 for communication and supports both stdio and HTTP transport mechanisms.', keyPoints: ['Client-server architecture', 'Clients: Claude Code, Claude Desktop, custom apps', 'Servers expose resources, tools, prompts', 'JSON-RPC 2.0 communication', 'Transport: stdio and HTTP'], order: 2 },
    { moduleId: 5, title: 'MCP Primitives', content: 'MCP defines three main primitives: Resources (data the model can read), Tools (functions the model can call), and Prompts (reusable prompt templates). Resources are identified by URIs, tools have JSON Schema definitions, and prompts can accept arguments.', keyPoints: ['Resources: data access via URIs', 'Tools: callable functions with JSON Schema', 'Prompts: reusable templates with arguments', 'Each primitive has specific lifecycle', 'Servers advertise capabilities at initialization'], order: 3 },

    // Module 6: MCP Advanced Topics
    { moduleId: 6, title: 'Building MCP Servers', content: 'MCP servers can be built using the official SDKs (TypeScript, Python, Java, Kotlin, C#, Rust). A server implements the MCP protocol, registers its capabilities, and handles client requests. Servers can be local (stdio) or remote (HTTP/SSE).', keyPoints: ['Official SDKs: TypeScript, Python, Java, C#, Rust', 'Implement MCP protocol handlers', 'Register resources, tools, prompts', 'Local (stdio) or remote (HTTP/SSE) deployment', 'Lifecycle: initialize, ready, shutdown'], order: 1 },
    { moduleId: 6, title: 'MCP Security Considerations', keyPoints: ['Validate all tool inputs server-side', 'Implement authentication for remote servers', 'Principle of least privilege for tool access', 'Audit logging for tool invocations', 'Sandboxing for untrusted servers'], content: 'MCP security is critical since tools can execute arbitrary actions. Best practices include: validating all inputs server-side, implementing authentication for remote servers, applying principle of least privilege, maintaining audit logs, and sandboxing untrusted servers.', order: 2 },
    { moduleId: 6, title: 'MCP Ecosystem & Discovery', content: 'The MCP ecosystem includes hundreds of pre-built servers for databases, APIs, file systems, and development tools. Servers can be discovered via registries, package managers, or direct configuration. Claude Code and Claude Desktop support configuring MCP servers in their settings.', keyPoints: ['Hundreds of pre-built servers available', 'Databases, APIs, file systems, dev tools', 'Discovery via registries and package managers', 'Configuration in Claude Code/Desktop settings', 'Growing ecosystem with community contributions'], order: 3 },

    // Module 7: Introduction to Agent Skills
    { moduleId: 7, title: 'What are Agent Skills', content: 'Agent Skills are reusable, composable instruction sets that extend Claude\'s capabilities. They encapsulate domain knowledge, workflows, and best practices in a portable format. Skills can be shared across teams and projects, enabling consistent AI-assisted workflows.', keyPoints: ['Reusable instruction sets for Claude', 'Encapsulate domain knowledge and workflows', 'Portable and shareable format', 'Enable consistent AI-assisted workflows', 'Can include scripts, templates, references'], order: 1 },
    { moduleId: 7, title: 'Skill Structure', content: 'A skill is typically a markdown file (SKILL.md) with YAML frontmatter defining metadata (name, description, version) and a body containing instructions. Skills can reference supporting files like scripts, templates, and reference documents.', keyPoints: ['SKILL.md with YAML frontmatter', 'Metadata: name, description, version', 'Body with instructions and guidance', 'Can reference supporting files', 'Organized in skill directories'], order: 2 },
    { moduleId: 7, title: 'Skill Composition', content: 'Skills can be composed and chained together. A workflow might invoke multiple skills sequentially or conditionally. Claude can discover available skills and select the appropriate one based on the task context. This composition enables complex multi-step workflows.', keyPoints: ['Skills can be composed and chained', 'Sequential or conditional invocation', 'Claude discovers and selects skills', 'Enables complex multi-step workflows', 'Reduces prompt engineering overhead'], order: 3 },

    // Module 8: Introduction to Subagents
    { moduleId: 8, title: 'Subagent Architecture', content: 'Subagents are independent Claude instances spawned by a main agent to handle specific tasks. Each subagent has its own context window, tool access, and execution environment. The main agent orchestrates subagents, delegating tasks and aggregating results.', keyPoints: ['Independent Claude instances', 'Own context window and tools', 'Main agent orchestrates and delegates', 'Results aggregated by main agent', 'Enables parallel task execution'], order: 1 },
    { moduleId: 8, title: 'When to Use Subagents', content: 'Subagents are ideal for: parallel independent tasks, tasks requiring isolated context, long-running operations that would exhaust the main context window, specialized tasks needing different tool sets, and tasks requiring different model capabilities.', keyPoints: ['Parallel independent tasks', 'Isolated context requirements', 'Long-running operations', 'Different tool sets needed', 'Different model capabilities per task'], order: 2 },
    { moduleId: 8, title: 'Subagent Communication', content: 'Subagents communicate with the main agent through structured outputs. The main agent provides task specifications and receives results. Subagents cannot directly communicate with each other - all coordination flows through the main agent. This prevents race conditions and ensures deterministic orchestration.', keyPoints: ['Structured output communication', 'Task specs from main agent', 'Results returned to main agent', 'No direct subagent-to-subagent communication', 'Deterministic orchestration'], order: 3 },

    // Module 9: AI Fluency Foundations
    { moduleId: 9, title: 'AI Fluency Framework', content: 'The AI Fluency framework defines four pillars: Know (understanding AI capabilities and limitations), Envision (identifying AI opportunities), Build (creating AI solutions), and Govern (responsible AI use). It provides a structured approach to developing AI competency in individuals and organizations.', keyPoints: ['Four pillars: Know, Envision, Build, Govern', 'Structured AI competency development', 'Applies to individuals and organizations', 'Covers technical and ethical dimensions', 'Foundation for responsible AI adoption'], order: 1 },
    { moduleId: 9, title: 'Knowing AI Capabilities', content: 'The Know pillar focuses on understanding what AI can and cannot do. This includes knowledge of model architectures, training data limitations, context windows, reasoning capabilities, and the difference between pattern matching and true understanding.', keyPoints: ['Model architectures and training', 'Training data limitations and biases', 'Context window constraints', 'Reasoning vs pattern matching', 'Understanding hallucination risks'], order: 2 },
    { moduleId: 9, title: 'Governing AI Use', content: 'The Govern pillar addresses responsible AI deployment: bias mitigation, transparency, accountability, privacy, and compliance. It includes establishing AI policies, monitoring outputs, and ensuring human oversight for high-stakes decisions.', keyPoints: ['Bias mitigation strategies', 'Transparency and explainability', 'Accountability frameworks', 'Privacy and data protection', 'Human oversight for critical decisions'], order: 3 },

    // Module 10: Claude Cowork
    { moduleId: 10, title: 'What is Claude Cowork', content: 'Claude Cowork is Anthropic\'s framework for collaborative AI workflows where humans and Claude work together on tasks. It emphasizes human-in-the-loop patterns where AI handles routine aspects while humans provide judgment, creativity, and oversight.', keyPoints: ['Human-AI collaborative workflows', 'Human-in-the-loop patterns', 'AI handles routine, humans provide judgment', 'Emphasizes complementary strengths', 'Framework for productive collaboration'], order: 1 },
    { moduleId: 10, title: 'Cowork Patterns', content: 'Common Cowork patterns include: Draft-and-review (AI drafts, human reviews), Iterative refinement (back-and-forth improvement), Human-guided exploration (human directs, AI executes), and Parallel synthesis (AI generates options, human selects).', keyPoints: ['Draft-and-review pattern', 'Iterative refinement cycles', 'Human-guided exploration', 'Parallel synthesis and selection', 'Choosing the right pattern for the task'], order: 2 },
    { moduleId: 10, title: 'Effective Prompting for Cowork', content: 'Effective Cowork requires clear task specification, appropriate context provision, explicit quality criteria, and iterative feedback. The human role evolves from task definition to quality assurance to strategic direction as the collaboration matures.', keyPoints: ['Clear task specification', 'Appropriate context provision', 'Explicit quality criteria', 'Iterative feedback loops', 'Evolving human role in collaboration'], order: 3 },

    // Module 11: AI Capabilities & Limitations
    { moduleId: 11, title: 'Hallucinations', content: 'Hallucinations occur when Claude generates plausible but incorrect or fabricated information. This is an inherent limitation of language models. Mitigation strategies include: providing source material, asking for citations, using tool access to verify facts, and implementing human review for critical outputs.', keyPoints: ['Plausible but incorrect outputs', 'Inherent limitation of LLMs', 'Mitigation: provide source material', 'Ask for citations and sources', 'Tool access for fact verification'], order: 1 },
    { moduleId: 11, title: 'Reasoning Limitations', content: 'While Claude can perform complex reasoning, it has limitations: difficulty with very long logical chains, susceptibility to prompt injection, inconsistent performance on novel problem types, and no true understanding of causality. These limitations inform architectural decisions about when to trust AI outputs vs. require human verification.', keyPoints: ['Difficulty with very long logical chains', 'Susceptibility to prompt injection', 'Inconsistent on novel problem types', 'No true causal understanding', 'Architectural implications for trust'], order: 2 },
    { moduleId: 11, title: 'Knowledge Cutoff & Real-time Data', content: 'Claude has a knowledge cutoff date and cannot access real-time information without tool use. Applications requiring current data must integrate tools like web search, API calls, or database queries. This is a fundamental architectural consideration for production systems.', keyPoints: ['Knowledge cutoff date limitation', 'No real-time data without tools', 'Must integrate search/API tools', 'RAG for domain-specific current data', 'Fundamental architectural consideration'], order: 3 },

    // Module 12: Claude on Cloud Platforms
    { moduleId: 12, title: 'AWS Bedrock Integration', content: 'Amazon Bedrock provides Claude as a managed service with enterprise features: IAM-based authentication, VPC endpoints for private access, CloudWatch logging, and integration with AWS services (S3, Lambda, SageMaker). Bedrock supports both on-demand and provisioned throughput pricing.', keyPoints: ['Managed Claude service on AWS', 'IAM authentication and VPC endpoints', 'CloudWatch logging and monitoring', 'Integration with AWS ecosystem', 'On-demand and provisioned throughput'], order: 1 },
    { moduleId: 12, title: 'Google Cloud Vertex AI', content: 'Vertex AI provides Claude access through Model Garden with GCP-native features: IAM integration, VPC Service Controls, Cloud Logging, and integration with BigQuery, Cloud Functions, and other GCP services. Multi-cloud strategies can use both Bedrock and Vertex AI for redundancy.', keyPoints: ['Claude via Vertex AI Model Garden', 'GCP IAM and VPC Service Controls', 'Cloud Logging integration', 'BigQuery and Cloud Functions integration', 'Multi-cloud redundancy strategies'], order: 2 },
    { moduleId: 12, title: 'Cloud Architecture Patterns', content: 'Common patterns for cloud-deployed Claude applications: API Gateway + Lambda for serverless, containerized deployments on ECS/GKE, caching layers for repeated queries, queue-based processing for async workloads, and multi-region deployment for latency optimization.', keyPoints: ['Serverless: API Gateway + Lambda', 'Containerized: ECS/GKE deployments', 'Caching for repeated queries', 'Queue-based async processing', 'Multi-region for latency optimization'], order: 3 },

    // Module 13: Teaching AI Fluency
    { moduleId: 13, title: 'Teaching Strategies', content: 'Effective AI fluency teaching combines hands-on practice with conceptual understanding. Key strategies include: starting with low-stakes tasks, encouraging experimentation, providing structured frameworks for prompt engineering, and creating safe spaces for failure and learning.', keyPoints: ['Hands-on practice + conceptual understanding', 'Start with low-stakes tasks', 'Encourage experimentation', 'Structured prompt engineering frameworks', 'Safe spaces for learning from failure'], order: 1 },
    { moduleId: 13, title: 'Organizational AI Adoption', content: 'Organizational AI adoption requires: executive sponsorship, clear use case identification, pilot programs with measurable outcomes, training programs at all levels, governance frameworks, and continuous iteration based on feedback and results.', keyPoints: ['Executive sponsorship', 'Clear use case identification', 'Pilot programs with metrics', 'Training at all levels', 'Governance frameworks and iteration'], order: 2 },
    { moduleId: 13, title: 'Measuring AI Fluency', content: 'AI fluency can be measured through: self-assessment surveys, practical skill demonstrations, quality of AI-assisted outputs, efficiency gains in workflows, and ability to identify appropriate vs. inappropriate AI use cases. Regular assessment helps track progress and identify gaps.', keyPoints: ['Self-assessment surveys', 'Practical skill demonstrations', 'Output quality metrics', 'Workflow efficiency gains', 'Appropriate use case identification'], order: 3 },
  ];

  await db.flashcards.bulkAdd(flashcards);

  // Questions - 12+ per module = 156+ total
  const questions: any[] = [
    // Module 1: Claude 101 (12 questions)
    { moduleId: 1, question: 'Which Claude model is the most cost-effective for high-volume, simple tasks?', options: ['Claude Opus', 'Claude Sonnet', 'Claude Haiku', 'Claude Turbo'], correctIndex: 2, explanation: 'Claude Haiku is the fastest and most economical model, designed for high-volume tasks where speed and cost matter more than maximum capability.', difficulty: 'easy' },
    { moduleId: 1, question: 'What is the maximum context window size for Claude models?', options: ['100K tokens', '128K tokens', '200K tokens', '500K tokens'], correctIndex: 2, explanation: 'Claude models support up to 200K tokens context window, allowing processing of very long documents and conversations.', difficulty: 'easy' },
    { moduleId: 1, question: 'What does Constitutional AI refer to in the context of Claude?', options: ['A legal framework for AI regulation', 'Training approach focused on helpfulness, harmlessness, and honesty', 'A constitutional document for AI governance', 'A type of model architecture'], correctIndex: 1, explanation: 'Constitutional AI is Anthropic\'s training approach that aligns models to be helpful, harmless, and honest through techniques like RLHF and constitutional principles.', difficulty: 'medium' },
    { moduleId: 1, question: 'Which of the following is NOT a valid strategy for managing context window limitations?', options: ['Summarization of conversation history', 'Sliding window approach', 'Increasing the model\'s context window via API parameter', 'Retrieval Augmented Generation (RAG)'], correctIndex: 2, explanation: 'The context window is a fixed property of the model and cannot be increased via API parameter. You must manage context through strategies like summarization, sliding windows, or RAG.', difficulty: 'medium' },
    { moduleId: 1, question: 'When choosing between Claude Opus, Sonnet, and Haiku, what is the primary trade-off?', options: ['Speed vs. accuracy only', 'Capability vs. speed vs. cost', 'Language support vs. context window', 'Training data size vs. model size'], correctIndex: 1, explanation: 'The primary trade-off between Claude models is capability (reasoning, analysis) vs. speed (response time) vs. cost (per-token pricing). Opus is most capable but slowest and most expensive.', difficulty: 'easy' },
    { moduleId: 1, question: 'What happens when a conversation exceeds the context window limit?', options: ['The API returns an error', 'The model automatically summarizes older messages', 'Older messages are truncated and the model loses that context', 'The model stops responding'], correctIndex: 2, explanation: 'When the context window is exceeded, older messages are typically truncated, meaning the model loses awareness of earlier conversation context. Applications must manage this proactively.', difficulty: 'medium' },
    { moduleId: 1, question: 'Which Claude model would be best suited for a complex multi-step reasoning task requiring deep analysis?', options: ['Claude Haiku', 'Claude Sonnet', 'Claude Opus', 'Any model performs equally'], correctIndex: 2, explanation: 'Claude Opus is the most powerful model, designed for complex reasoning, deep analysis, and tasks requiring the highest level of capability.', difficulty: 'easy' },
    { moduleId: 1, question: 'What is a token in the context of Claude API?', options: ['A security credential for API access', 'A unit of text roughly equivalent to 4 characters or 3/4 of a word', 'A type of API response format', 'A model training parameter'], correctIndex: 1, explanation: 'A token is a unit of text - roughly 4 characters or 3/4 of an English word. Token count determines context window usage and API cost.', difficulty: 'easy' },
    { moduleId: 1, question: 'Which of the following is included in the token count against the context window?', options: ['Only user messages', 'Only the system prompt', 'System prompt, conversation history, tool definitions, and user input', 'Only the current user message'], correctIndex: 2, explanation: 'Everything sent to the API counts toward the context window: system prompt, all conversation history, tool definitions, and the current user input.', difficulty: 'medium' },
    { moduleId: 1, question: 'What is the primary benefit of using Claude Haiku over Claude Opus?', options: ['Better reasoning ability', 'Lower cost and faster response times', 'Larger context window', 'Better multilingual support'], correctIndex: 1, explanation: 'Claude Haiku\'s primary advantages are significantly lower cost and faster response times, making it ideal for high-volume, straightforward tasks.', difficulty: 'easy' },
    { moduleId: 1, question: 'How does Claude handle multi-turn conversations?', options: ['Each request is stateless and independent', 'The entire conversation history must be sent with each request', 'Claude maintains server-side memory of conversations', 'Only the last 3 messages are retained'], correctIndex: 1, explanation: 'Claude\'s API is stateless. For multi-turn conversations, the application must send the entire conversation history with each request to maintain context.', difficulty: 'medium' },
    { moduleId: 1, question: 'What is the recommended approach when building an application that needs to process documents longer than the context window?', options: ['Split the document into chunks and process separately with summarization', 'Use a different AI service', 'Compress the document text to fit', 'Increase the context window via API configuration'], correctIndex: 0, explanation: 'For documents exceeding the context window, the recommended approach is to split into chunks, process separately, and use summarization or RAG to maintain understanding of the full document.', difficulty: 'hard' },

    // Module 2: Claude Code 101 (12 questions)
    { moduleId: 2, question: 'What is Claude Code?', options: ['A web-based code editor', 'A terminal-based agentic coding assistant', 'A VS Code extension only', 'A code review service'], correctIndex: 1, explanation: 'Claude Code is a terminal-based agentic coding assistant that can read codebases, edit files, run commands, and execute multi-step development tasks.', difficulty: 'easy' },
    { moduleId: 2, question: 'Which file is used to provide persistent project-level instructions to Claude Code?', options: ['CLAUDE.txt', 'CLAUDE.md', 'claude.config', 'claude.yaml'], correctIndex: 1, explanation: 'CLAUDE.md is a markdown file placed in the project root that provides persistent instructions, coding standards, and behavioral guidelines to Claude Code.', difficulty: 'easy' },
    { moduleId: 2, question: 'What permission system does Claude Code use?', options: ['No permissions - full access by default', 'Role-based access control', 'Granular permissions for reads, writes, commands, and network', 'Read-only mode only'], correctIndex: 2, explanation: 'Claude Code uses a granular permission system controlling file reads, file writes, bash commands, and network requests. Users can approve or deny each action.', difficulty: 'medium' },
    { moduleId: 2, question: 'How can Claude Code be integrated into CI/CD pipelines?', options: ['It cannot be used in CI/CD', 'Through the headless mode using the -p flag', 'Only through the interactive terminal', 'Through a web API'], correctIndex: 1, explanation: 'Claude Code supports headless mode via the -p flag, allowing it to accept a prompt and return output programmatically, enabling CI/CD integration.', difficulty: 'medium' },
    { moduleId: 2, question: 'Where can Claude Code permissions be configured for a project?', options: ['In the Anthropic dashboard', 'In .claude/settings.json', 'In the system environment variables', 'In the Claude API key settings'], correctIndex: 1, explanation: 'Project-level permissions and configuration for Claude Code can be set in .claude/settings.json or through CLAUDE.md in the project root.', difficulty: 'easy' },
    { moduleId: 2, question: 'Which of the following is NOT a capability of Claude Code?', options: ['Reading and editing files', 'Running shell commands', 'Deploying to production servers autonomously', 'Understanding project context and dependencies'], correctIndex: 2, explanation: 'While Claude Code can run commands and edit files, deploying to production should always involve human oversight. Claude Code assists with development tasks but doesn\'t autonomously deploy to production.', difficulty: 'medium' },
    { moduleId: 2, question: 'What is the primary difference between Claude Code and a code completion tool?', options: ['Claude Code is faster', 'Claude Code is agentic - it can execute multi-step tasks autonomously', 'Claude Code only works with Python', 'There is no difference'], correctIndex: 1, explanation: 'Unlike simple code completion, Claude Code is agentic - it can understand entire projects, plan multi-step tasks, and execute them autonomously including file edits and command execution.', difficulty: 'easy' },
    { moduleId: 2, question: 'What format is CLAUDE.md written in?', options: ['JSON', 'YAML', 'Markdown', 'TOML'], correctIndex: 2, explanation: 'CLAUDE.md is written in Markdown format, making it easy to read and write while supporting structured content like headers, lists, and code blocks.', difficulty: 'easy' },
    { moduleId: 2, question: 'Which statement about Claude Code\'s context is true?', options: ['It can only see the current file', 'It can read and understand the entire codebase', 'It has no access to the file system', 'It can only read files, not edit them'], correctIndex: 1, explanation: 'Claude Code can read and understand the entire codebase, enabling it to make contextually aware changes across multiple files while understanding dependencies.', difficulty: 'medium' },
    { moduleId: 2, question: 'What happens when Claude Code attempts an action that requires permission?', options: ['It proceeds automatically', 'It asks for user approval (in interactive mode)', 'It skips the action', 'It terminates the session'], correctIndex: 1, explanation: 'In interactive mode, Claude Code asks for user approval before executing actions that require permission. In headless mode, pre-configured permissions determine what\'s allowed.', difficulty: 'easy' },
    { moduleId: 2, question: 'Which of the following can be specified in CLAUDE.md?', options: ['Only coding standards', 'Only project structure', 'Coding standards, project architecture, preferred libraries, and behavioral guidelines', 'Only API keys and secrets'], correctIndex: 2, explanation: 'CLAUDE.md can specify coding standards, project architecture, preferred libraries, behavioral guidelines, and any other project-specific instructions.', difficulty: 'medium' },
    { moduleId: 2, question: 'How does Claude Code handle multi-file changes for a single task?', options: ['It can only edit one file at a time', 'It understands dependencies and makes consistent changes across files', 'It requires manual coordination between files', 'It creates new files but cannot modify existing ones'], correctIndex: 1, explanation: 'Claude Code understands dependencies between files and can make consistent, coordinated changes across multiple files for a single task (e.g., adding an endpoint updates routes, handlers, and tests).', difficulty: 'hard' },

    // Module 3: Claude Code in Action (12 questions)
    { moduleId: 3, question: 'What is a custom skill in Claude Code?', options: ['A programming language feature', 'A reusable instruction set that extends Claude Code capabilities', 'A type of API key', 'A model training technique'], correctIndex: 1, explanation: 'Custom skills are reusable instruction sets (typically markdown files) that extend Claude Code\'s capabilities with domain-specific knowledge and workflows.', difficulty: 'easy' },
    { moduleId: 3, question: 'When adding a new API endpoint, what files might Claude Code modify?', options: ['Only the route handler', 'Route handler, router, tests, and data model', 'Only the database schema', 'Only the API documentation'], correctIndex: 1, explanation: 'Claude Code can coordinate changes across multiple files: creating the route handler, updating the router configuration, adding tests, and modifying the data model as needed.', difficulty: 'medium' },
    { moduleId: 3, question: 'What is the -p flag used for in Claude Code?', options: ['To print the conversation', 'To run in headless mode with a prompt', 'To set permissions', 'To specify a project directory'], correctIndex: 1, explanation: 'The -p flag runs Claude Code in headless mode, accepting a prompt string and returning the output programmatically, enabling CI/CD and automation integration.', difficulty: 'easy' },
    { moduleId: 3, question: 'Which of the following is a valid use case for Claude Code headless mode?', options: ['Interactive debugging', 'Automated code review in CI/CD', 'Pair programming', 'Learning to code'], correctIndex: 1, explanation: 'Headless mode is ideal for automated workflows like CI/CD code review, batch processing, and automated testing where human interaction is not needed.', difficulty: 'medium' },
    { moduleId: 3, question: 'How do custom skills benefit development teams?', options: ['They replace the need for documentation', 'They encode domain-specific knowledge and ensure consistent workflows', 'They automatically fix all bugs', 'They reduce API costs'], correctIndex: 1, explanation: 'Custom skills encode domain-specific knowledge, best practices, and workflows in a reusable format, ensuring consistent AI-assisted development across the team.', difficulty: 'medium' },
    { moduleId: 3, question: 'What can custom skills include?', options: ['Only text instructions', 'Instructions, scripts, templates, and reference materials', 'Only code snippets', 'Only API documentation'], correctIndex: 1, explanation: 'Custom skills can include text instructions, executable scripts, code templates, reference materials, and any supporting files needed for the workflow.', difficulty: 'easy' },
    { moduleId: 3, question: 'Which pattern best describes Claude Code\'s approach to complex refactoring?', options: ['Make all changes in a single file first', 'Understand dependencies, plan changes, execute consistently across files', 'Only refactor one function at a time', 'Require manual verification after each line change'], correctIndex: 1, explanation: 'Claude Code understands cross-file dependencies, plans refactoring changes, and executes them consistently across all affected files.', difficulty: 'hard' },
    { moduleId: 3, question: 'What is the benefit of using Claude Code over manual coding for repetitive tasks?', options: ['It eliminates all bugs', 'It reduces manual coordination overhead and maintains consistency', 'It is always faster than humans', 'It requires no review'], correctIndex: 1, explanation: 'Claude Code reduces manual coordination overhead for repetitive tasks and maintains consistency across files, though human review is still recommended.', difficulty: 'easy' },
    { moduleId: 3, question: 'How should custom skills be organized in a project?', options: ['In a single monolithic file', 'In a skills directory with separate files per skill', 'In the .env file', 'In the package.json'], correctIndex: 1, explanation: 'Custom skills should be organized in a skills directory with separate markdown files for each skill, making them easy to discover, maintain, and share.', difficulty: 'medium' },
    { moduleId: 3, question: 'Which of the following is true about Claude Code\'s headless mode output?', options: ['It returns only exit codes', 'It returns structured text output that can be parsed by scripts', 'It only works with JSON format', 'It cannot be captured programmatically'], correctIndex: 1, explanation: 'Headless mode returns structured text output that can be captured and parsed by scripts, enabling integration into automated workflows.', difficulty: 'medium' },
    { moduleId: 3, question: 'What is a key consideration when using Claude Code for large-scale refactoring?', options: ['It should always be done without human review', 'Changes should be reviewed and tested, especially for critical systems', 'It can only refactor one file at a time', 'It cannot handle refactoring'], correctIndex: 1, explanation: 'While Claude Code can handle large-scale refactoring, changes should always be reviewed and tested, especially for critical production systems.', difficulty: 'medium' },
    { moduleId: 3, question: 'How does Claude Code maintain code style consistency across edits?', options: ['It ignores existing code style', 'It reads existing code and matches the established patterns', 'It always uses its own preferred style', 'It requires a style configuration file'], correctIndex: 1, explanation: 'Claude Code reads the existing codebase and matches established coding patterns, conventions, and style when making edits, ensuring consistency.', difficulty: 'hard' },

    // Module 4: Building with the Claude API (12 questions)
    { moduleId: 4, question: 'What is the primary API endpoint for interacting with Claude?', options: ['/v1/chat', '/v1/messages', '/v1/completions', '/v1/generate'], correctIndex: 1, explanation: 'The Messages API (/v1/messages) is the primary interface for interacting with Claude, accepting message arrays and returning completions.', difficulty: 'easy' },
    { moduleId: 4, question: 'How is authentication handled for the Claude API?', options: ['OAuth 2.0', 'Bearer token in Authorization header', 'x-api-key header', 'Query parameter'], correctIndex: 2, explanation: 'Claude API uses the x-api-key header with your Anthropic API key for authentication.', difficulty: 'easy' },
    { moduleId: 4, question: 'What is the role of the system parameter in the Messages API?', options: ['It specifies the model version', 'It provides behavioral instructions and context for Claude', 'It sets the response format', 'It determines the API endpoint'], correctIndex: 1, explanation: 'The system parameter provides behavioral instructions, context, and guidelines that shape how Claude responds throughout the conversation.', difficulty: 'easy' },
    { moduleId: 4, question: 'In the tool use flow, what does the application do after receiving a tool_use block from Claude?', options: ['Ignore the tool_use block', 'Execute the tool and return the result as tool_result', 'Send a new user message', 'End the conversation'], correctIndex: 1, explanation: 'When Claude generates a tool_use block, the application must execute the specified tool with the provided parameters and return the result as a tool_result in the next request.', difficulty: 'medium' },
    { moduleId: 4, question: 'What transport mechanism does streaming use in the Claude API?', options: ['WebSocket', 'Server-Sent Events (SSE)', 'Long polling', 'gRPC'], correctIndex: 1, explanation: 'Claude API streaming uses Server-Sent Events (SSE) to deliver tokens as they are generated in real-time.', difficulty: 'medium' },
    { moduleId: 4, question: 'Which event type in streaming indicates new text content?', options: ['message_start', 'content_block_delta', 'message_stop', 'ping'], correctIndex: 1, explanation: 'The content_block_delta event contains new text tokens as they are generated during streaming.', difficulty: 'medium' },
    { moduleId: 4, question: 'What is the correct sequence for a tool use interaction?', options: ['User message -> Tool result -> Assistant response', 'User message -> Assistant tool_use -> Tool execution -> Tool result -> Assistant response', 'Tool execution -> User message -> Assistant response', 'Assistant response -> Tool execution -> User message'], correctIndex: 1, explanation: 'The correct flow is: User sends message -> Claude responds with tool_use -> Application executes tool -> Application sends tool_result -> Claude continues with final response.', difficulty: 'hard' },
    { moduleId: 4, question: 'What happens if you exceed your API rate limit?', options: ['Requests are queued automatically', 'You receive a 429 HTTP status code', 'The API returns cached responses', 'Your account is suspended'], correctIndex: 1, explanation: 'Exceeding rate limits returns a 429 HTTP status code. Production applications should implement retry logic with exponential backoff.', difficulty: 'medium' },
    { moduleId: 4, question: 'Which of the following is NOT a valid content type in the Messages API?', options: ['text', 'image', 'tool_use', 'audio'], correctIndex: 3, explanation: 'The Messages API supports text, image, tool_use, and tool_result content types. Audio is not a supported content type in the Messages API.', difficulty: 'hard' },
    { moduleId: 4, question: 'What is the purpose of the max_tokens parameter?', options: ['To set the context window size', 'To limit the maximum length of Claude\'s response', 'To control API rate limits', 'To specify the number of messages'], correctIndex: 1, explanation: 'max_tokens limits the maximum number of tokens in Claude\'s response, helping control costs and response length.', difficulty: 'easy' },
    { moduleId: 4, question: 'How should you handle multi-turn conversations with the Claude API?', options: ['Use the conversation_id parameter', 'Maintain the message history client-side and send it with each request', 'Use server-side sessions', 'Claude automatically remembers conversations'], correctIndex: 1, explanation: 'The Claude API is stateless. Applications must maintain conversation history client-side and include all previous messages with each request.', difficulty: 'medium' },
    { moduleId: 4, question: 'What is the temperature parameter used for?', options: ['To control API server temperature', 'To control randomness/creativity in responses', 'To set the response timeout', 'To determine token pricing'], correctIndex: 1, explanation: 'Temperature controls randomness in Claude\'s responses. Lower values (0) produce more deterministic outputs, higher values (1) produce more creative/varied outputs.', difficulty: 'easy' },

    // Module 5: Introduction to MCP (12 questions)
    { moduleId: 5, question: 'What does MCP stand for?', options: ['Model Configuration Protocol', 'Model Context Protocol', 'Multi-Client Platform', 'Model Control Plane'], correctIndex: 1, explanation: 'MCP stands for Model Context Protocol - an open protocol for connecting AI applications to external data sources and tools.', difficulty: 'easy' },
    { moduleId: 5, question: 'Who originally introduced MCP?', options: ['OpenAI', 'Google', 'Anthropic', 'Microsoft'], correctIndex: 2, explanation: 'MCP was introduced by Anthropic and has since become an open standard with broad industry adoption.', difficulty: 'easy' },
    { moduleId: 5, question: 'What communication protocol does MCP use?', options: ['REST', 'GraphQL', 'JSON-RPC 2.0', 'gRPC'], correctIndex: 2, explanation: 'MCP uses JSON-RPC 2.0 for communication between clients and servers.', difficulty: 'medium' },
    { moduleId: 5, question: 'What are the two transport mechanisms supported by MCP?', options: ['WebSocket and REST', 'stdio and HTTP', 'TCP and UDP', 'gRPC and GraphQL'], correctIndex: 1, explanation: 'MCP supports stdio (for local servers) and HTTP/SSE (for remote servers) as transport mechanisms.', difficulty: 'medium' },
    { moduleId: 5, question: 'Which of the following is NOT an MCP primitive?', options: ['Resources', 'Tools', 'Prompts', 'Models'], correctIndex: 3, explanation: 'MCP defines three primitives: Resources (data access), Tools (function calls), and Prompts (reusable templates). Models are not an MCP primitive.', difficulty: 'medium' },
    { moduleId: 5, question: 'How are Resources identified in MCP?', options: ['By integer IDs', 'By URI strings', 'By JSON paths', 'By table names'], correctIndex: 1, explanation: 'Resources in MCP are identified by URI strings (e.g., file:///path/to/file, db://table/row).', difficulty: 'medium' },
    { moduleId: 5, question: 'What format is used to define tool parameters in MCP?', options: ['Protocol Buffers', 'JSON Schema', 'XML Schema', 'YAML'], correctIndex: 1, explanation: 'Tool parameters in MCP are defined using JSON Schema, providing a standardized way to describe input types and constraints.', difficulty: 'medium' },
    { moduleId: 5, question: 'In MCP architecture, what is the role of a client?', options: ['To provide data storage', 'To connect to MCP servers and consume their capabilities', 'To train AI models', 'To manage API keys'], correctIndex: 1, explanation: 'MCP clients (like Claude Code, Claude Desktop) connect to MCP servers to access their resources, tools, and prompts.', difficulty: 'easy' },
    { moduleId: 5, question: 'What is the MCP initialization sequence?', options: ['Connect -> Authenticate -> Use', 'Initialize -> Capabilities exchange -> Ready', 'Handshake -> Authorize -> Start', 'Register -> Discover -> Execute'], correctIndex: 1, explanation: 'MCP initialization follows: client sends initialize request, server responds with capabilities, client sends initialized notification, connection is ready.', difficulty: 'hard' },
    { moduleId: 5, question: 'Which applications can act as MCP clients?', options: ['Only Claude Desktop', 'Only Claude Code', 'Claude Code, Claude Desktop, and any MCP-compatible application', 'Only custom-built applications'], correctIndex: 2, explanation: 'Any application implementing the MCP client protocol can connect to MCP servers, including Claude Code, Claude Desktop, and custom applications.', difficulty: 'easy' },
    { moduleId: 5, question: 'What is the purpose of MCP Prompts?', options: ['To send messages to users', 'To provide reusable prompt templates that can accept arguments', 'To configure model parameters', 'To define system prompts only'], correctIndex: 1, explanation: 'MCP Prompts are reusable prompt templates that clients can discover and invoke with arguments, standardizing common interaction patterns.', difficulty: 'medium' },
    { moduleId: 5, question: 'How does MCP improve upon ad-hoc AI integrations?', options: ['By being faster', 'By providing a standardized protocol that any client can use with any server', 'By being free', 'By requiring less code'], correctIndex: 1, explanation: 'MCP replaces ad-hoc integrations with a standardized protocol, allowing any MCP client to connect to any MCP server without custom integration code.', difficulty: 'easy' },

    // Module 6: MCP Advanced Topics (12 questions)
    { moduleId: 6, question: 'Which SDKs are officially available for building MCP servers?', options: ['Only Python', 'Only TypeScript', 'TypeScript, Python, Java, Kotlin, C#, Rust', 'Only JavaScript'], correctIndex: 2, explanation: 'Official MCP SDKs are available for TypeScript, Python, Java, Kotlin, C#, and Rust, enabling server development in multiple languages.', difficulty: 'medium' },
    { moduleId: 6, question: 'What is a key security best practice for MCP servers?', options: ['Allow all tool inputs without validation', 'Validate all tool inputs server-side', 'Disable authentication for local servers', 'Trust all client requests'], correctIndex: 1, explanation: 'All tool inputs should be validated server-side to prevent injection attacks and ensure data integrity, regardless of the client.', difficulty: 'medium' },
    { moduleId: 6, question: 'How should remote MCP servers handle authentication?', options: ['No authentication needed', 'Implement proper authentication (API keys, OAuth, etc.)', 'Only use IP whitelisting', 'Authentication is handled by the MCP protocol'], correctIndex: 1, explanation: 'Remote MCP servers should implement proper authentication mechanisms like API keys or OAuth to control access.', difficulty: 'medium' },
    { moduleId: 6, question: 'What is the principle of least privilege in MCP context?', options: ['Give servers maximum access', 'Only expose tools and resources that are necessary', 'Use the cheapest model', 'Minimize the number of servers'], correctIndex: 1, explanation: 'MCP servers should only expose the minimum set of tools and resources needed, reducing the attack surface and potential for misuse.', difficulty: 'medium' },
    { moduleId: 6, question: 'How can MCP servers be discovered?', options: ['Through DNS records', 'Via registries, package managers, or direct configuration', 'They cannot be discovered', 'Through the Anthropic API'], correctIndex: 1, explanation: 'MCP servers can be discovered through community registries, package managers (npm, pip), or direct configuration in client applications.', difficulty: 'easy' },
    { moduleId: 6, question: 'What is the difference between stdio and HTTP MCP servers?', options: ['There is no difference', 'stdio servers run locally as subprocesses; HTTP servers run remotely', 'stdio is faster', 'HTTP servers are more secure'], correctIndex: 1, explanation: 'stdio MCP servers run as local subprocesses communicating via standard I/O, while HTTP servers run as remote services communicating over HTTP/SSE.', difficulty: 'medium' },
    { moduleId: 6, question: 'Why is audit logging important for MCP servers?', options: ['It is not important', 'To track tool invocations for security and debugging', 'To increase server performance', 'To reduce network traffic'], correctIndex: 1, explanation: 'Audit logging tracks which tools were invoked, by whom, and with what parameters, enabling security monitoring and debugging.', difficulty: 'medium' },
    { moduleId: 6, question: 'What is sandboxing in the context of MCP?', options: ['Running servers in isolated environments to limit potential damage', 'Using sand-colored UI themes', 'A type of caching', 'A deployment strategy'], correctIndex: 0, explanation: 'Sandboxing runs MCP servers in isolated environments, limiting their access to system resources and containing potential security breaches.', difficulty: 'hard' },
    { moduleId: 6, question: 'How do you configure MCP servers in Claude Code?', options: ['Through the Anthropic dashboard', 'In .claude/settings.json or CLAUDE.md', 'Via environment variables only', 'Through the MCP registry'], correctIndex: 1, explanation: 'MCP servers are configured in Claude Code through .claude/settings.json or CLAUDE.md, specifying the server command and arguments.', difficulty: 'medium' },
    { moduleId: 6, question: 'Which of the following is a valid use case for an MCP server?', options: ['Only database access', 'Database access, API integration, file system access, and custom tooling', 'Only web scraping', 'Only code execution'], correctIndex: 1, explanation: 'MCP servers can provide access to databases, APIs, file systems, custom tools, and any external system that AI applications need to interact with.', difficulty: 'easy' },
    { moduleId: 6, question: 'What happens if an MCP server crashes during a session?', options: ['The client automatically restarts it', 'The client loses connection and must reconnect', 'All data is lost permanently', 'The client switches to a backup server automatically'], correctIndex: 1, explanation: 'If an MCP server crashes, the client loses the connection. The application should implement reconnection logic to handle server failures gracefully.', difficulty: 'hard' },
    { moduleId: 6, question: 'What is the recommended approach for deploying MCP servers in production?', options: ['Run everything on a single server', 'Use containerization, monitoring, and proper security controls', 'Deploy without authentication', 'Use only stdio transport'], correctIndex: 1, explanation: 'Production MCP servers should use containerization for isolation, monitoring for observability, and proper security controls including authentication and input validation.', difficulty: 'hard' },

    // Module 7: Introduction to Agent Skills (12 questions)
    { moduleId: 7, question: 'What is an Agent Skill?', options: ['A programming language feature', 'A reusable instruction set that extends Claude\'s capabilities', 'A type of neural network layer', 'A model training technique'], correctIndex: 1, explanation: 'Agent Skills are reusable, composable instruction sets that extend Claude\'s capabilities with domain knowledge and workflows.', difficulty: 'easy' },
    { moduleId: 7, question: 'What file format is typically used for Agent Skills?', options: ['JSON', 'YAML', 'Markdown (SKILL.md)', 'XML'], correctIndex: 2, explanation: 'Agent Skills are typically defined in SKILL.md files - markdown with YAML frontmatter for metadata and markdown body for instructions.', difficulty: 'easy' },
    { moduleId: 7, question: 'What information is typically included in the YAML frontmatter of a skill?', options: ['Only the skill name', 'Name, description, version, and other metadata', 'API keys and secrets', 'Database connection strings'], correctIndex: 1, explanation: 'YAML frontmatter typically includes name, description, version, author, and other metadata that helps discover and manage skills.', difficulty: 'medium' },
    { moduleId: 7, question: 'How can skills be composed?', options: ['They cannot be composed', 'Sequentially or conditionally chained together', 'Only in parallel', 'Only two skills can be combined'], correctIndex: 1, explanation: 'Skills can be composed sequentially (one after another) or conditionally (based on context), enabling complex multi-step workflows.', difficulty: 'medium' },
    { moduleId: 7, question: 'What is the primary benefit of using skills over inline prompts?', options: ['Skills are always shorter', 'Skills are reusable, shareable, and maintainable', 'Skills execute faster', 'Skills require less context'], correctIndex: 1, explanation: 'Skills provide reusability across projects and teams, maintainability through version control, and shareability as portable instruction sets.', difficulty: 'easy' },
    { moduleId: 7, question: 'Which of the following can a skill reference?', options: ['Only text files', 'Scripts, templates, and reference materials', 'Only code files', 'Only images'], correctIndex: 1, explanation: 'Skills can reference supporting files including scripts, templates, reference documents, and other resources needed for the workflow.', difficulty: 'medium' },
    { moduleId: 7, question: 'How does Claude discover available skills?', options: ['Through a central registry', 'By reading the skills directory in the project', 'Skills are automatically downloaded', 'Through the Anthropic API'], correctIndex: 1, explanation: 'Claude discovers skills by reading the skills directory in the project, loading available skill definitions as needed.', difficulty: 'medium' },
    { moduleId: 7, question: 'What is the difference between a skill and a prompt template?', options: ['There is no difference', 'Skills can include scripts, references, and multi-step workflows; prompt templates are just text', 'Skills are shorter', 'Prompt templates are more powerful'], correctIndex: 1, explanation: 'Skills are more comprehensive than prompt templates - they can include scripts, reference materials, and multi-step workflows, not just text instructions.', difficulty: 'medium' },
    { moduleId: 7, question: 'When should you create a custom skill?', options: ['For every interaction', 'When you have a reusable workflow or domain knowledge that extends Claude\'s capabilities', 'Only for complex tasks', 'Never - use only built-in capabilities'], correctIndex: 1, explanation: 'Create custom skills when you have reusable workflows, domain-specific knowledge, or patterns that you want to consistently apply across tasks.', difficulty: 'easy' },
    { moduleId: 7, question: 'How do skills reduce prompt engineering overhead?', options: ['They don\'t', 'By encapsulating common patterns that can be reused without rewriting prompts', 'By making prompts shorter', 'By eliminating the need for prompts'], correctIndex: 1, explanation: 'Skills encapsulate proven patterns and domain knowledge, so users don\'t need to rewrite detailed prompts for common tasks - they just invoke the skill.', difficulty: 'medium' },
    { moduleId: 7, question: 'Which of the following is a valid skill category?', options: ['Only development skills', 'Development, data analysis, content creation, and domain-specific skills', 'Only coding skills', 'Skills cannot be categorized'], correctIndex: 1, explanation: 'Skills can cover any domain: development, data analysis, content creation, research, and any specialized domain knowledge.', difficulty: 'easy' },
    { moduleId: 7, question: 'What happens when multiple skills could apply to a task?', options: ['An error occurs', 'Claude selects the most appropriate skill based on context', 'All skills are applied simultaneously', 'The first skill in alphabetical order is used'], correctIndex: 1, explanation: 'When multiple skills could apply, Claude evaluates the task context and selects the most appropriate skill to use.', difficulty: 'hard' },

    // Module 8: Introduction to Subagents (12 questions)
    { moduleId: 8, question: 'What is a subagent?', options: ['A smaller AI model', 'An independent Claude instance spawned by a main agent for specific tasks', 'A type of API endpoint', 'A user role in Claude Code'], correctIndex: 1, explanation: 'Subagents are independent Claude instances spawned by a main agent to handle specific tasks, each with their own context window and execution environment.', difficulty: 'easy' },
    { moduleId: 8, question: 'What is the main benefit of using subagents?', options: ['They are cheaper', 'They enable parallel execution and isolated context for complex tasks', 'They are faster than the main agent', 'They require less configuration'], correctIndex: 1, explanation: 'Subagents enable parallel execution of independent tasks and provide isolated context windows, preventing the main agent\'s context from being exhausted.', difficulty: 'medium' },
    { moduleId: 8, question: 'Can subagents communicate directly with each other?', options: ['Yes, freely', 'No - all coordination flows through the main agent', 'Only via shared files', 'Only via the network'], correctIndex: 1, explanation: 'Subagents cannot communicate directly with each other. All coordination flows through the main agent, preventing race conditions and ensuring deterministic orchestration.', difficulty: 'medium' },
    { moduleId: 8, question: 'When should you use subagents instead of the main agent?', options: ['Always', 'For parallel independent tasks, isolated context needs, or long-running operations', 'Only for simple tasks', 'Never'], correctIndex: 1, explanation: 'Use subagents for parallel independent tasks, tasks requiring isolated context, long-running operations, or when different tool sets are needed.', difficulty: 'medium' },
    { moduleId: 8, question: 'How does the main agent receive results from subagents?', options: ['Via email', 'Through structured output from the subagent', 'Via a database', 'Results are not returned'], correctIndex: 1, explanation: 'Subagents return structured output to the main agent, which aggregates and synthesizes the results.', difficulty: 'medium' },
    { moduleId: 8, question: 'What is a key architectural pattern for subagent orchestration?', options: ['All subagents run sequentially', 'Main agent delegates, subagents execute independently, results are aggregated', 'Subagents control the main agent', 'Subagents share a single context window'], correctIndex: 1, explanation: 'The pattern is: main agent delegates tasks to subagents, subagents execute independently, and the main agent aggregates the results.', difficulty: 'hard' },
    { moduleId: 8, question: 'What happens if a subagent fails?', options: ['The entire system crashes', 'The main agent can handle the failure and retry or use alternative approaches', 'All other subagents stop', 'The failure is ignored'], correctIndex: 1, explanation: 'The main agent should handle subagent failures gracefully, with retry logic or alternative approaches for fault tolerance.', difficulty: 'hard' },
    { moduleId: 8, question: 'Which of the following is a valid use case for subagents?', options: ['Only code generation', 'Parallel code review of multiple files, independent research tasks, specialized analysis', 'Only simple tasks', 'Only tasks requiring internet access'], correctIndex: 1, explanation: 'Subagents excel at parallel code review, independent research tasks, specialized analysis, and any work that can be done independently.', difficulty: 'medium' },
    { moduleId: 8, question: 'How does using subagents help with context window management?', options: ['It doesn\'t', 'Each subagent has its own context window, preventing the main agent\'s context from filling up', 'Subagents share the main agent\'s context', 'Subagents have unlimited context'], correctIndex: 1, explanation: 'Each subagent has its own context window, so their work doesn\'t consume the main agent\'s limited context space.', difficulty: 'medium' },
    { moduleId: 8, question: 'What information does the main agent provide to a subagent?', options: ['Nothing - subagents work independently', 'Task specifications, relevant context, and expected output format', 'Only the task name', 'The entire conversation history'], correctIndex: 1, explanation: 'The main agent provides task specifications, relevant context, and expected output format to each subagent to ensure focused and useful results.', difficulty: 'medium' },
    { moduleId: 8, question: 'Which statement about subagent execution is true?', options: ['Subagents always run sequentially', 'Subagents can run in parallel for independent tasks', 'Subagents are limited to 3 concurrent instances', 'Subagents can only run on remote servers'], correctIndex: 1, explanation: 'Subagents can run in parallel when tasks are independent, significantly reducing total execution time for complex multi-part work.', difficulty: 'medium' },
    { moduleId: 8, question: 'What is the fan-out/fan-in pattern in subagent orchestration?', options: ['A cooling system for servers', 'Main agent fans out tasks to multiple subagents, then fans in results', 'A network topology', 'A data compression technique'], correctIndex: 1, explanation: 'Fan-out/fan-in: the main agent distributes (fans out) tasks to multiple subagents, then collects and aggregates (fans in) their results.', difficulty: 'hard' },

    // Module 9: AI Fluency Foundations (12 questions)
    { moduleId: 9, question: 'What are the four pillars of the AI Fluency framework?', options: ['Read, Write, Execute, Debug', 'Know, Envision, Build, Govern', 'Plan, Do, Check, Act', 'Input, Process, Output, Feedback'], correctIndex: 1, explanation: 'The AI Fluency framework has four pillars: Know (understand AI), Envision (identify opportunities), Build (create solutions), and Govern (responsible use).', difficulty: 'easy' },
    { moduleId: 9, question: 'What does the "Know" pillar focus on?', options: ['Knowing how to code', 'Understanding AI capabilities and limitations', 'Knowing all AI models', 'Knowing API endpoints'], correctIndex: 1, explanation: 'The Know pillar focuses on understanding what AI can and cannot do, including model capabilities, limitations, and appropriate use cases.', difficulty: 'easy' },
    { moduleId: 9, question: 'What does the "Envision" pillar involve?', options: ['Creating visual designs', 'Identifying opportunities where AI can add value', 'Predicting the future of AI', 'Building prototypes'], correctIndex: 1, explanation: 'The Envision pillar involves identifying opportunities where AI can improve workflows, solve problems, or create value.', difficulty: 'easy' },
    { moduleId: 9, question: 'What does the "Build" pillar cover?', options: ['Only software development', 'Creating AI solutions, including prompt engineering and system design', 'Only model training', 'Only infrastructure setup'], correctIndex: 1, explanation: 'The Build pillar covers creating AI solutions: prompt engineering, system design, integration, and deployment of AI-powered applications.', difficulty: 'medium' },
    { moduleId: 9, question: 'What does the "Govern" pillar address?', options: ['Only legal compliance', 'Responsible AI use: bias, transparency, accountability, privacy', 'Only data governance', 'Only model governance'], correctIndex: 1, explanation: 'The Govern pillar addresses responsible AI use including bias mitigation, transparency, accountability, privacy, and establishing AI policies.', difficulty: 'medium' },
    { moduleId: 9, question: 'Why is understanding AI limitations important?', options: ['It is not important', 'To make informed decisions about when to trust AI outputs vs. require human verification', 'To avoid using AI entirely', 'To reduce costs'], correctIndex: 1, explanation: 'Understanding limitations helps architects design systems that appropriately use AI strengths while mitigating weaknesses through human oversight and verification.', difficulty: 'medium' },
    { moduleId: 9, question: 'What is a key aspect of the Govern pillar?', options: ['Maximizing AI usage', 'Establishing human oversight for high-stakes decisions', 'Eliminating human involvement', 'Using the most powerful model available'], correctIndex: 1, explanation: 'The Govern pillar emphasizes human oversight for high-stakes decisions, ensuring AI augments rather than replaces human judgment in critical contexts.', difficulty: 'medium' },
    { moduleId: 9, question: 'How does AI fluency benefit organizations?', options: ['It doesn\'t', 'Enables effective identification and implementation of AI solutions while managing risks', 'Only reduces costs', 'Only improves technical skills'], correctIndex: 1, explanation: 'AI fluency enables organizations to effectively identify AI opportunities, build appropriate solutions, and manage risks through governance.', difficulty: 'medium' },
    { moduleId: 9, question: 'What is the relationship between AI fluency and responsible AI?', options: ['They are unrelated', 'AI fluency includes governance as a core pillar, ensuring responsible use', 'AI fluency is only about technical skills', 'Responsible AI limits AI fluency'], correctIndex: 1, explanation: 'AI fluency inherently includes responsible AI through the Govern pillar, ensuring that technical capability is paired with ethical considerations.', difficulty: 'medium' },
    { moduleId: 9, question: 'Which pillar would involve identifying that a customer service workflow could benefit from AI?', options: ['Know', 'Envision', 'Build', 'Govern'], correctIndex: 1, explanation: 'Identifying AI opportunities in existing workflows is part of the Envision pillar - seeing where AI can add value.', difficulty: 'easy' },
    { moduleId: 9, question: 'Which pillar would involve implementing bias detection in an AI system?', options: ['Know', 'Envision', 'Build', 'Govern'], correctIndex: 3, explanation: 'Implementing bias detection and mitigation falls under the Govern pillar, which addresses responsible AI deployment.', difficulty: 'medium' },
    { moduleId: 9, question: 'What is the ultimate goal of AI fluency?', options: ['To replace humans with AI', 'To enable effective, responsible collaboration between humans and AI', 'To build the most powerful AI systems', 'To eliminate all AI risks'], correctIndex: 1, explanation: 'The ultimate goal of AI fluency is enabling effective, responsible collaboration between humans and AI, leveraging the strengths of both.', difficulty: 'easy' },

    // Module 10: Claude Cowork (12 questions)
    { moduleId: 10, question: 'What is Claude Cowork?', options: ['A job board for AI engineers', 'A framework for human-AI collaborative workflows', 'A type of AI model', 'A project management tool'], correctIndex: 1, explanation: 'Claude Cowork is Anthropic\'s framework for collaborative AI workflows where humans and Claude work together, each contributing their strengths.', difficulty: 'easy' },
    { moduleId: 10, question: 'What is the "Draft-and-review" pattern?', options: ['Writing documentation only', 'AI drafts content, human reviews and refines it', 'Human drafts, AI reviews', 'A code review process'], correctIndex: 1, explanation: 'In Draft-and-review, Claude generates initial drafts which humans then review, edit, and refine - combining AI speed with human judgment.', difficulty: 'medium' },
    { moduleId: 10, question: 'What is the "Iterative refinement" pattern?', options: ['One-shot generation', 'Back-and-forth improvement between human and AI', 'Only human refinement', 'Only AI refinement'], correctIndex: 1, explanation: 'Iterative refinement involves cycles of human feedback and AI improvement, progressively enhancing the output through collaboration.', difficulty: 'medium' },
    { moduleId: 10, question: 'What is "Human-guided exploration"?', options: ['AI explores autonomously', 'Human directs the exploration, AI executes and provides results', 'Random exploration', 'Only human exploration'], correctIndex: 1, explanation: 'In Human-guided exploration, the human provides direction and strategy while AI handles execution and provides detailed results.', difficulty: 'medium' },
    { moduleId: 10, question: 'What is "Parallel synthesis"?', options: ['Sequential task execution', 'AI generates multiple options, human selects the best one', 'Only human generation', 'Only AI selection'], correctIndex: 1, explanation: 'In Parallel synthesis, Claude generates multiple alternatives or approaches, and the human selects or combines the best elements.', difficulty: 'medium' },
    { moduleId: 10, question: 'What is a key principle of effective Cowork?', options: ['Let AI do everything', 'Leverage complementary strengths of human and AI', 'Minimize human involvement', 'Always use the most powerful model'], correctIndex: 1, explanation: 'Effective Cowork leverages complementary strengths: AI handles routine tasks, data processing, and generation while humans provide judgment, creativity, and oversight.', difficulty: 'easy' },
    { moduleId: 10, question: 'How does the human role evolve in a Cowork collaboration?', options: ['It stays the same throughout', 'From task definition to quality assurance to strategic direction', 'From strategic to operational', 'The human role diminishes over time'], correctIndex: 1, explanation: 'The human role evolves from initial task definition, through quality assurance of outputs, to providing strategic direction as the collaboration matures.', difficulty: 'hard' },
    { moduleId: 10, question: 'What makes a good Cowork prompt?', options: ['Being as vague as possible', 'Clear task specification, appropriate context, and explicit quality criteria', 'Using only technical jargon', 'Making prompts as long as possible'], correctIndex: 1, explanation: 'Good Cowork prompts include clear task specification, relevant context, and explicit quality criteria to guide Claude\'s contributions effectively.', difficulty: 'medium' },
    { moduleId: 10, question: 'Which Cowork pattern is best for generating creative content options?', options: ['Draft-and-review', 'Parallel synthesis', 'Human-guided exploration', 'Iterative refinement'], correctIndex: 1, explanation: 'Parallel synthesis is ideal for generating multiple creative options, allowing the human to select or combine the best elements.', difficulty: 'medium' },
    { moduleId: 10, question: 'Which Cowork pattern is best for improving an existing document?', options: ['Parallel synthesis', 'Iterative refinement', 'Human-guided exploration', 'None of the above'], correctIndex: 1, explanation: 'Iterative refinement is best for improving existing documents through cycles of feedback and enhancement.', difficulty: 'easy' },
    { moduleId: 10, question: 'What is the primary risk of not having clear quality criteria in Cowork?', options: ['AI will refuse to work', 'Outputs may not meet expectations, requiring more revision cycles', 'The API will return errors', 'Costs will increase dramatically'], correctIndex: 1, explanation: 'Without clear quality criteria, Claude\'s outputs may not align with expectations, leading to more revision cycles and less efficient collaboration.', difficulty: 'medium' },
    { moduleId: 10, question: 'How does Cowork differ from fully autonomous AI operation?', options: ['There is no difference', 'Cowork maintains human involvement and oversight throughout', 'Cowork is slower', 'Cowork uses different models'], correctIndex: 1, explanation: 'Cowork maintains active human involvement and oversight, unlike fully autonomous operation where AI works without human guidance.', difficulty: 'easy' },

    // Module 11: AI Capabilities & Limitations (12 questions)
    { moduleId: 11, question: 'What is a hallucination in the context of AI?', options: ['A visual artifact in generated images', 'Generating plausible but incorrect or fabricated information', 'A type of model architecture', 'A training technique'], correctIndex: 1, explanation: 'Hallucinations occur when Claude generates information that sounds plausible but is actually incorrect or fabricated - an inherent limitation of language models.', difficulty: 'easy' },
    { moduleId: 11, question: 'Which is NOT a mitigation strategy for hallucinations?', options: ['Providing source material for Claude to reference', 'Asking Claude to cite its sources', 'Blindly trusting all AI outputs', 'Using tool access to verify facts'], correctIndex: 2, explanation: 'Blindly trusting AI outputs is not a mitigation strategy - it\'s a risk. Effective mitigations include providing sources, asking for citations, and verifying facts through tools.', difficulty: 'easy' },
    { moduleId: 11, question: 'What is Claude\'s knowledge cutoff?', options: ['The maximum context window size', 'The date after which Claude has no training data', 'The rate limit threshold', 'The maximum number of API calls'], correctIndex: 1, explanation: 'The knowledge cutoff is the date after which Claude has no training data. Information after this date is unknown to Claude unless provided via tools or context.', difficulty: 'medium' },
    { moduleId: 11, question: 'How should an application handle real-time data requirements?', options: ['Use only Claude\'s built-in knowledge', 'Integrate tools like web search, API calls, or database queries', 'Wait for model retraining', 'Real-time data is not possible'], correctIndex: 1, explanation: 'Applications requiring real-time data must integrate tools (web search, APIs, databases) since Claude\'s knowledge has a cutoff date.', difficulty: 'medium' },
    { moduleId: 11, question: 'What is prompt injection?', options: ['A method to improve prompts', 'An attack where malicious instructions are embedded in user input or documents', 'A type of API call', 'A model training technique'], correctIndex: 1, explanation: 'Prompt injection is an attack where malicious instructions are embedded in user input or documents, attempting to override Claude\'s intended behavior.', difficulty: 'hard' },
    { moduleId: 11, question: 'Which of the following is a reasoning limitation of Claude?', options: ['Cannot do any math', 'Difficulty with very long logical chains', 'Cannot understand code', 'Cannot process images'], correctIndex: 1, explanation: 'While Claude is capable at reasoning, it can struggle with very long logical chains that require maintaining many intermediate steps.', difficulty: 'medium' },
    { moduleId: 11, question: 'What is Retrieval Augmented Generation (RAG)?', options: ['A model training technique', 'Retrieving relevant documents and including them in the context for more accurate responses', 'A type of API endpoint', 'A caching mechanism'], correctIndex: 1, explanation: 'RAG retrieves relevant documents from a knowledge base and includes them in the context, enabling Claude to provide accurate, up-to-date information.', difficulty: 'medium' },
    { moduleId: 11, question: 'Why is it important to understand AI limitations when architecting systems?', options: ['It is not important', 'To design appropriate safeguards, verification steps, and human oversight', 'To avoid using AI entirely', 'To reduce API costs'], correctIndex: 1, explanation: 'Understanding limitations informs architectural decisions about when to trust AI outputs, when to add verification steps, and where human oversight is needed.', difficulty: 'medium' },
    { moduleId: 11, question: 'What is the difference between pattern matching and true understanding in AI?', options: ['There is no difference', 'Pattern matching recognizes statistical regularities; true understanding involves causal reasoning', 'Pattern matching is better', 'True understanding is just more pattern matching'], correctIndex: 1, explanation: 'Claude uses pattern matching on training data rather than true causal understanding. This distinction is important for knowing when outputs may be unreliable.', difficulty: 'hard' },
    { moduleId: 11, question: 'Which architectural pattern helps mitigate knowledge cutoff limitations?', options: ['Using only the largest model', 'RAG and tool integration for current data', 'Increasing the context window', 'Using multiple models simultaneously'], correctIndex: 1, explanation: 'RAG and tool integration allow Claude to access current information beyond its training cutoff, mitigating knowledge limitations.', difficulty: 'medium' },
    { moduleId: 11, question: 'What should you do when Claude says "I don\'t know"?', options: ['Assume the answer doesn\'t exist', 'This is a sign of appropriate uncertainty - verify through other sources', 'Retry the same question', 'Switch to a different model'], correctIndex: 1, explanation: 'When Claude expresses uncertainty, it\'s appropriately signaling limitation. Verify through other sources rather than assuming the answer doesn\'t exist.', difficulty: 'easy' },
    { moduleId: 11, question: 'How does Constitutional AI help with limitations?', options: ['It eliminates all limitations', 'It trains Claude to be more honest about what it doesn\'t know', 'It increases the context window', 'It provides real-time data access'], correctIndex: 1, explanation: 'Constitutional AI trains Claude to be more honest about uncertainties and limitations, making it more reliable about what it does and doesn\'t know.', difficulty: 'medium' },

    // Module 12: Claude on Cloud Platforms (12 questions)
    { moduleId: 12, question: 'What is Amazon Bedrock?', options: ['A database service', 'A managed AI service providing access to foundation models including Claude', 'A storage service', 'A networking service'], correctIndex: 1, explanation: 'Amazon Bedrock is a managed service that provides access to foundation models including Claude, with enterprise features like IAM authentication and VPC endpoints.', difficulty: 'easy' },
    { moduleId: 12, question: 'How does AWS Bedrock authenticate API requests to Claude?', options: ['x-api-key header', 'AWS IAM credentials and SigV4 signing', 'OAuth 2.0 only', 'No authentication required'], correctIndex: 1, explanation: 'AWS Bedrock uses AWS IAM credentials with SigV4 request signing for authentication, integrating with existing AWS security infrastructure.', difficulty: 'medium' },
    { moduleId: 12, question: 'What is a key advantage of using Bedrock over direct Anthropic API?', options: ['Lower prices always', 'Enterprise features: IAM, VPC endpoints, CloudWatch, AWS service integration', 'Better model quality', 'Faster response times'], correctIndex: 1, explanation: 'Bedrock provides enterprise features like IAM authentication, VPC endpoints for private access, CloudWatch logging, and integration with AWS services.', difficulty: 'medium' },
    { moduleId: 12, question: 'What is Google Cloud Vertex AI?', options: ['A storage service', 'Google\'s managed AI platform providing access to models including Claude via Model Garden', 'A networking service', 'A database service'], correctIndex: 1, explanation: 'Vertex AI is Google\'s managed AI platform. Claude is available through Model Garden with GCP-native features like IAM and VPC Service Controls.', difficulty: 'easy' },
    { moduleId: 12, question: 'What is VPC Service Controls in the context of Vertex AI?', options: ['A load balancing feature', 'Security controls that create service perimeters to protect AI resources', 'A model training feature', 'A caching mechanism'], correctIndex: 1, explanation: 'VPC Service Controls create security perimeters around GCP resources, preventing data exfiltration and controlling access to AI services.', difficulty: 'hard' },
    { moduleId: 12, question: 'Which architecture pattern is common for serverless Claude deployments?', options: ['Monolithic application', 'API Gateway + Lambda', 'Direct EC2 instances only', 'On-premise only'], correctIndex: 1, explanation: 'API Gateway + Lambda is a common serverless pattern for Claude deployments, providing auto-scaling and pay-per-use pricing.', difficulty: 'medium' },
    { moduleId: 12, question: 'What is provisioned throughput in Bedrock?', options: ['Unlimited free usage', 'Reserved capacity for predictable performance at a fixed cost', 'A type of caching', 'A security feature'], correctIndex: 1, explanation: 'Provisioned throughput reserves model capacity for predictable performance, useful for production workloads with consistent traffic patterns.', difficulty: 'medium' },
    { moduleId: 12, question: 'Why might an organization choose multi-cloud deployment for Claude?', options: ['To double costs', 'For redundancy, vendor flexibility, and regional availability', 'It is not possible', 'Multi-cloud is always worse'], correctIndex: 1, explanation: 'Multi-cloud deployment provides redundancy, avoids vendor lock-in, and can optimize for regional availability and latency.', difficulty: 'medium' },
    { moduleId: 12, question: 'Which AWS service would you use to monitor Claude API usage in Bedrock?', options: ['S3', 'CloudWatch', 'Lambda', 'DynamoDB'], correctIndex: 1, explanation: 'CloudWatch provides logging and monitoring for Bedrock API calls, enabling observability and alerting.', difficulty: 'easy' },
    { moduleId: 12, question: 'What is a caching layer used for in Claude cloud deployments?', options: ['To store API keys', 'To cache repeated queries and reduce API calls and costs', 'To increase latency', 'To bypass authentication'], correctIndex: 1, explanation: 'Caching layers store responses to repeated queries, reducing API calls, latency, and costs for frequently requested information.', difficulty: 'medium' },
    { moduleId: 12, question: 'Which pattern is best for async processing of Claude requests?', options: ['Synchronous API calls only', 'Queue-based processing (SQS, Pub/Sub)', 'Direct database writes', 'Email-based processing'], correctIndex: 1, explanation: 'Queue-based processing (SQS, Pub/Sub) handles async Claude requests, enabling background processing and handling traffic spikes.', difficulty: 'medium' },
    { moduleId: 12, question: 'What is the benefit of using containerized deployments (ECS/GKE) for Claude applications?', options: ['No benefit', 'Scalability, isolation, and consistent environments', 'Lower API costs', 'Better model quality'], correctIndex: 1, explanation: 'Containerized deployments provide scalability through auto-scaling, isolation between services, and consistent environments across development and production.', difficulty: 'hard' },

    // Module 13: Teaching AI Fluency (12 questions)
    { moduleId: 13, question: 'What is the recommended starting point for teaching AI fluency?', options: ['Advanced model architecture', 'Low-stakes, practical hands-on tasks', 'Theoretical research papers', 'Complex production systems'], correctIndex: 1, explanation: 'Start with low-stakes, practical tasks to build confidence and understanding before moving to complex applications.', difficulty: 'easy' },
    { moduleId: 13, question: 'Why is encouraging experimentation important in AI fluency training?', options: ['It wastes time', 'Hands-on experimentation builds practical understanding and confidence', 'Experimentation is dangerous', 'Only experts should experiment'], correctIndex: 1, explanation: 'Experimentation builds practical understanding of AI capabilities and limitations, and creates safe spaces for learning from both successes and failures.', difficulty: 'easy' },
    { moduleId: 13, question: 'What is a structured framework for prompt engineering?', options: ['Random prompting', 'Role-Task-Format-Context frameworks or similar structured approaches', 'Using only single-word prompts', 'Avoiding any structure'], correctIndex: 1, explanation: 'Structured frameworks like Role-Task-Format-Context help users create effective prompts consistently, improving AI interaction quality.', difficulty: 'medium' },
    { moduleId: 13, question: 'What is the role of executive sponsorship in organizational AI adoption?', options: ['No role', 'Provides strategic direction, resources, and organizational support', 'Only technical implementation', 'Only budget approval'], correctIndex: 1, explanation: 'Executive sponsorship provides strategic direction, allocates resources, and signals organizational commitment to AI adoption.', difficulty: 'medium' },
    { moduleId: 13, question: 'Why are pilot programs important for organizational AI adoption?', options: ['They are not important', 'They provide measurable outcomes and learning before full-scale deployment', 'They delay adoption', 'They increase costs without benefit'], correctIndex: 1, explanation: 'Pilot programs provide measurable outcomes, identify challenges, and generate learning before committing to full-scale AI deployment.', difficulty: 'medium' },
    { moduleId: 13, question: 'How can AI fluency be measured?', options: ['It cannot be measured', 'Through self-assessments, practical demonstrations, output quality, and efficiency gains', 'Only through tests', 'Only through API usage metrics'], correctIndex: 1, explanation: 'AI fluency can be measured through self-assessment surveys, practical skill demonstrations, quality of AI-assisted outputs, and workflow efficiency gains.', difficulty: 'medium' },
    { moduleId: 13, question: 'What is a key success factor for AI training programs?', options: ['Making training mandatory only', 'Combining conceptual understanding with hands-on practice', 'Focusing only on theory', 'Focusing only on tools'], correctIndex: 1, explanation: 'Effective AI training combines conceptual understanding (knowing why) with hands-on practice (knowing how) for comprehensive skill development.', difficulty: 'medium' },
    { moduleId: 13, question: 'Why is continuous iteration important in AI adoption?', options: ['It is not important', 'AI technology and best practices evolve rapidly, requiring ongoing adaptation', 'Iteration wastes resources', 'Initial deployment is always perfect'], correctIndex: 1, explanation: 'AI technology evolves rapidly. Continuous iteration based on feedback and results ensures the organization stays current and optimizes AI use.', difficulty: 'medium' },
    { moduleId: 13, question: 'What is the benefit of creating safe spaces for AI learning?', options: ['No benefit', 'Encourages experimentation and learning from failure without fear', 'Increases costs', 'Slows down adoption'], correctIndex: 1, explanation: 'Safe spaces encourage experimentation and learning from failure, which are essential for developing practical AI skills and confidence.', difficulty: 'easy' },
    { moduleId: 13, question: 'Which of the following is a governance framework component for organizational AI?', options: ['No governance needed', 'AI policies, monitoring, and accountability structures', 'Only technical documentation', 'Only budget tracking'], correctIndex: 1, explanation: 'Governance frameworks include AI policies, output monitoring, accountability structures, and compliance mechanisms for responsible AI use.', difficulty: 'medium' },
    { moduleId: 13, question: 'What is the relationship between AI fluency and innovation?', options: ['They are unrelated', 'Higher AI fluency enables better identification and implementation of AI-driven innovations', 'AI fluency limits innovation', 'Only technical staff need fluency for innovation'], correctIndex: 1, explanation: 'Higher AI fluency across the organization enables better identification of AI opportunities and more effective implementation of AI-driven innovations.', difficulty: 'medium' },
    { moduleId: 13, question: 'How should organizations approach AI fluency for different roles?', options: ['Everyone gets the same training', 'Tailored training based on role-specific AI interaction needs', 'Only technical staff need training', 'Training is optional'], correctIndex: 1, explanation: 'AI fluency training should be tailored to role-specific needs - developers need technical depth, managers need strategic understanding, users need practical skills.', difficulty: 'hard' },
  ];

  await db.questions.bulkAdd(questions);
}
